version: '3'

services:
  web:
    image: myapp
    ports:
      - '5000:5000'
    depends_on:
      - redis
  redis:
    image: redis
    volumes:
      - 'redis:/data'
    ports:
      - '6379:6379'

volumes:
  redis: